[package]
name = "standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmer = "6.1.0"
wasmer-wasix = "0.601.0"
anyhow = "1.0"
tokio = { version = "1.39.0", default-features = false }
openssl = { version = "0.10", features = ["vendored"] }
