[package]
name = "reva-client-eth"
description = ""
edition = "2021"

[dependencies]
bincode = "1.3.3"

# workspace
reva-client-executor.workspace = true

# Statically turns off logging
log = { version = "0.4", features = ["max_level_off", "release_max_level_off"] }
tracing = { version = "0.1", features = ["max_level_off", "release_max_level_off"] }

